name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  hello-world:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        with:
          input_secret: ${{ secrets.SEGREDO_SECRETO }} # SECRET AS AN INPUT FOR ACTION
        uses: actions/checkout@v4

      - name: Run a one-line script
        env:
          environment_variable_secret: ${{ secrets.SEGREDO_SECRETO }} # SECRET AS ENVIRONMENT VARIABLE
        run: echo Hello, world!

      - name: Run a one-line script with GitHub Actions
        uses: actions/github-script@v7
        with:
          input_secret: ${{ secrets.SEGREDO_SECRETO }} # SECRET AS AN INPUT FOR ACTION
          script: echo Hello, world with GitHub Actions!

      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
